### ISSUE TITLE
Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by lore6673** [Anchormen/sql4es#10]
Hi
I'm trying to use the driver with SQLWorkbenchJ and SquirrelSQL but I get several errors:

SQLWorkbenchJ give me a generic error: Unable to connect to DB.
SquirrelSQL, after defining the driver conf, give me the error: Unsupported major.minor version 52.0.

I'm using Mac OSX 10.11.5 and Java VM 1.7.

Thank you
Lorenzo

**Comment by corneversloot** [comment]
Hi, 
There is a dependency within sql4es which requires java 8 and I guess that throws this exception. When you upgrade to java 1.8 it should work.

 - Corne

**Comment by lore6673** [comment]
Thank you. I have verified and SQLWorkbench is using Java 1.8. But I get the error Unable to Connect to DB. I'm sure the parameters I'm using are correct.
Lorenzo

**Comment by lore6673** [comment]
I compiled a quick Java Class and I get the following exception...

java.sql.SQLException: Unable to connect to database
	at nl.anchormen.sql4es.jdbc.ESConnection.buildClient(ESConnection.java:129)
	at nl.anchormen.sql4es.jdbc.ESConnection.<init>(ESConnection.java:78)
	at nl.anchormen.sql4es.jdbc.ESDriver.connect(ESDriver.java:46)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at Test.main(Test.java:12)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{10.3.247.73}{10.3.247.73:9200}]]
	at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:290)
	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:207)
	at org.elasticsearch.client.transport.support.TransportProxyClient.execute(TransportProxyClient.java:55)
	at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:288)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:359)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:348)
	at org.elasticsearch.client.support.AbstractClient$IndicesAdmin.execute(AbstractClient.java:1221)
	at org.elasticsearch.client.support.AbstractClient$IndicesAdmin.exists(AbstractClient.java:1241)
	at nl.anchormen.sql4es.jdbc.ESConnection.buildClient(ESConnection.java:122)
	... 10 more

**Comment by corneversloot** [comment]
Well, the stacktrace indicates that it cannot find the elasticsearch nodes specified: _Caused by: NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{10.3.247.73}{10.3.247.73:9200}]]_

You should try port 9300 so it will connect to the transport endpoint (assuming that it uses default port 9300 on your elasticsearch cluster). Please post your url if this does not work so i can view exactly what how you connect to the cluster

**Comment by samuraraujo** [comment]
I have same issues using elasticsearch 2.3.2 and 2.3.3. 

Connection url:
jdbc:sql4es://localhost:9300

java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.sql.SQLException: Unable to connect to specified elasticsearch host(s)
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at net.sourceforge.squirrel_sql.client.mainframe.action.OpenConnectionCommand.awaitConnection(OpenConnectionCommand.java:132)
	at net.sourceforge.squirrel_sql.client.mainframe.action.OpenConnectionCommand.access$100(OpenConnectionCommand.java:45)
	at net.sourceforge.squirrel_sql.client.mainframe.action.OpenConnectionCommand$2.run(OpenConnectionCommand.java:115)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: java.sql.SQLException: Unable to connect to specified elasticsearch host(s)
	at net.sourceforge.squirrel_sql.client.mainframe.action.OpenConnectionCommand.executeConnect(OpenConnectionCommand.java:171)
	at net.sourceforge.squirrel_sql.client.mainframe.action.OpenConnectionCommand.access$000(OpenConnectionCommand.java:45)
	at net.sourceforge.squirrel_sql.client.mainframe.action.OpenConnectionCommand$1.run(OpenConnectionCommand.java:104)
	... 5 more
Caused by: java.sql.SQLException: Unable to connect to specified elasticsearch host(s)
	at nl.anchormen.sql4es.jdbc.ESConnection.<init>(ESConnection.java:82)
	at nl.anchormen.sql4es.jdbc.ESDriver.connect(ESDriver.java:46)
	at net.sourceforge.squirrel_sql.fw.sql.SQLDriverManager.getConnection(SQLDriverManager.java:133)
	at net.sourceforge.squirrel_sql.client.mainframe.action.OpenConnectionCommand.executeConnect(OpenConnectionCommand.java:167)
	... 7 more
Caused by: java.sql.SQLException: Unable to retrieve table data
	at nl.anchormen.sql4es.ESDatabaseMetaData.getColumns(ESDatabaseMetaData.java:964)
	at nl.anchormen.sql4es.jdbc.ESConnection.getTypeMap(ESConnection.java:278)
	at nl.anchormen.sql4es.jdbc.ESConnection.<init>(ESConnection.java:80)
	... 10 more
Caused by: NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{127.0.0.1}{localhost/127.0.0.1:9300}]]
	at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:290)
	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:207)
	at org.elasticsearch.client.transport.support.TransportProxyClient.execute(TransportProxyClient.java:55)
	at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:288)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:359)
	at org.elasticsearch.client.support.AbstractClient$ClusterAdmin.execute(AbstractClient.java:853)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:86)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:56)
	at org.elasticsearch.action.ActionRequestBuilder.get(ActionRequestBuilder.java:64)
	at nl.anchormen.sql4es.ESDatabaseMetaData.getColumns(ESDatabaseMetaData.java:913)
	... 12 more

Any possible solutions?

**Comment by corneversloot** [comment]
Closing due to inactivity.
