### ISSUE TITLE
Any plan to support 2.3.3?

### ISSUE THREAD

**Issue by samuraraujo** [Anchormen/sql4es#11]
Any plan to support 2.3.3?

**Comment by corneversloot** [comment]
I have updated to Elasticsearch 2.3.3 and tests ran without any issues. You can test the latest release (0.8.2.3) to see if it works for you. Let me know if you run into any issues!

**Comment by samuraraujo** [comment]
Thanks for the reply. 

I have same issue using elasticsearch 2.3.2 and 2.3.3.

Connection url:
jdbc:sql4es://localhost:9300

java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.sql.SQLException: Unable to connect to specified elasticsearch host(s)
at java.util.concurrent.FutureTask.report(FutureTask.java:122)
at java.util.concurrent.FutureTask.get(FutureTask.java:206)
at net.sourceforge.squirrel_sql.client.mainframe.action.OpenConnectionCommand.awaitConnection(OpenConnectionCommand.java:132)
at net.sourceforge.squirrel_sql.client.mainframe.action.OpenConnectionCommand.access$100(OpenConnectionCommand.java:45)
at net.sourceforge.squirrel_sql.client.mainframe.action.OpenConnectionCommand$2.run(OpenConnectionCommand.java:115)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: java.sql.SQLException: Unable to connect to specified elasticsearch host(s)
at net.sourceforge.squirrel_sql.client.mainframe.action.OpenConnectionCommand.executeConnect(OpenConnectionCommand.java:171)
at net.sourceforge.squirrel_sql.client.mainframe.action.OpenConnectionCommand.access$000(OpenConnectionCommand.java:45)
at net.sourceforge.squirrel_sql.client.mainframe.action.OpenConnectionCommand$1.run(OpenConnectionCommand.java:104)
... 5 more
Caused by: java.sql.SQLException: Unable to connect to specified elasticsearch host(s)
at nl.anchormen.sql4es.jdbc.ESConnection.(ESConnection.java:82)
at nl.anchormen.sql4es.jdbc.ESDriver.connect(ESDriver.java:46)
at net.sourceforge.squirrel_sql.fw.sql.SQLDriverManager.getConnection(SQLDriverManager.java:133)
at net.sourceforge.squirrel_sql.client.mainframe.action.OpenConnectionCommand.executeConnect(OpenConnectionCommand.java:167)
... 7 more
Caused by: java.sql.SQLException: Unable to retrieve table data
at nl.anchormen.sql4es.ESDatabaseMetaData.getColumns(ESDatabaseMetaData.java:964)
at nl.anchormen.sql4es.jdbc.ESConnection.getTypeMap(ESConnection.java:278)
at nl.anchormen.sql4es.jdbc.ESConnection.(ESConnection.java:80)
... 10 more
Caused by: NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{127.0.0.1}{localhost/127.0.0.1:9300}]]
at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:290)
at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:207)
at org.elasticsearch.client.transport.support.TransportProxyClient.execute(TransportProxyClient.java:55)
at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:288)
at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:359)
at org.elasticsearch.client.support.AbstractClient$ClusterAdmin.execute(AbstractClient.java:853)
at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:86)
at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:56)
at org.elasticsearch.action.ActionRequestBuilder.get(ActionRequestBuilder.java:64)
at nl.anchormen.sql4es.ESDatabaseMetaData.getColumns(ESDatabaseMetaData.java:913)
... 12 more

Any possible solutions?

**Comment by corneversloot** [comment]
Looks like the driver is unable to connect to your ES instance. One issue I can think of is the cluster name. If your cluster has another name than the default one 'elasticsearch'. If you have another name you must specify it using _jdbc:sql4es://localhost:9300/cluster.name=my_cluster_name_. Hope this helps!

**Comment by samuraraujo** [comment]
The cluster name is the default. i am running the default elastic downloaded as a tar file.

To reproduce the error, you can download the ES and run it as ./bin/elasticsearch.
Then try to connect with SQuirreL.

**Comment by corneversloot** [comment]
I tried connecting it but ran into the exact same error you report. I also tried it using SqlWorkbenchJ and that works as it is supposed to.

It seems SQuirreL runs into a conflict on Lucene libraries under the hood which causes it to fail. Ill try to fix it. In the mean time you can try working with SQLWorkbenchJ

**Comment by samuraraujo** [comment]
Hi Corne, it does not work with SQLWorkbenchJ either. :(

Let me know if you can fix it.

Best,

**Comment by csdharma** [comment]
How to specify the connection url for elasticsearch clusters with two nodes.

**Comment by corneversloot** [comment]
Hi Dharma,

Under the hood we use the original Elasticsearch library which discovers other nodes that can be used. In addition you can provide other hosts by adding the es.hosts parameter in the connection url with a comma separated list of alternative hosts: *dbc:sql4es://localhost:9300/myidx?es.hosts=other-host:9300,another-host-2.com:9301*
Adding hosts like this will protect the driver from failure in case the primary host is down

Cheers,
Corné

**Comment by csdharma** [comment]
Hi Corne,

Thanks for the response. I tried working with the below URL.
jdbc:sql4es://192.168.57.74:9300/appbiidx?cluster.name=appDataSuite,es.hosts=192.168.57.75:9300
 where 192.168.57.74 adn 192.168.57.75 are my two elasticsearch nodes under appDataSuite cluster.
I got the following error.

Caused by: NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{192.168.57.74}{192.168.57.74:9300}]]

Could you please help me out.

Moreover I need a clarification on the fetching part. I am able to fetch only 10000 records. Beyond which I need to iterate. Is there any specific reason behind it?

Regards, 
Dharma

**Comment by corneversloot** [comment]
There is a typo in the url you posted but i doubt that causes the error you get. You have a comma between your clustername and the es.hosts. This should be a '&' like this
dbc:sql4es://192.168.57.74:9300/appbiidx?cluster.name=appDataSuite**&**es.hosts=192.168.57.75:9300

Have you tried to connect to your hosts individually without using the es.hosts parameter (just to make sure there is no firewall or whatever blocking your)?

The 10000 records is a limit set by Elasticsearch and there is no way to get around it. You have to iterate in order to fetch more results. 

I hope this helps

**Comment by csdharma** [comment]
Oops.. I made the mistake. I changed as per your advice. It worked. Thank you Corne.

**Comment by csdharma** [comment]
Hi Corne,
Just got struck with another query. Is your driver support BETWEEN Clause? We need to use between for date fields. Also the date grouping based on month (JAN, FEB etc.)

Regards,

M. Dharma Raja

**Comment by corneversloot** [comment]
Hi Dharma,
I have added support for BETWEEN and (NOT BETWEEN) in the latest build which you can try (version 0.8.2.3). It simply parses the provided condition into an Elasticsearch range query which will include the specified minimum and maximum values in its selection. I have tested it briefly on numbers and dates but not on strings.

As far as i know grouping on an aspect of a date is not possible on the date object itself. You will have to add a field for the information you want to group on. In your case that should be the month number or name.

**Comment by csdharma** [comment]
Thanks Corne. Let me check and get back to you.

**Comment by csdharma** [comment]
Hi Corne,
Works fine. Appreciate your help. Thank You.
Regards,
Dharma

**Comment by corneversloot** [comment]
You are welcome.
