### ISSUE TITLE
Unexpected Error occurred attempting to open an SQL connection.

### ISSUE THREAD

**Issue by sundeepkmr** [Anchormen/sql4es#24]
Trying to configure in Virtual Desktop environment and getting the following error (using SQuirreL). Any help please?

java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.sql.SQLException: Unable to connect to database
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:206)
    at net.sourceforge.squirrel_sql.client.mainframe.action.OpenConnectionCommand.awaitConnection(OpenConnectionCommand.java:132)
    at net.sourceforge.squirrel_sql.client.mainframe.action.OpenConnectionCommand.access$100(OpenConnectionCommand.java:45)
    at net.sourceforge.squirrel_sql.client.mainframe.action.OpenConnectionCommand$2.run(OpenConnectionCommand.java:115)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: java.sql.SQLException: Unable to connect to database
    at net.sourceforge.squirrel_sql.client.mainframe.action.OpenConnectionCommand.executeConnect(OpenConnectionCommand.java:171)
    at net.sourceforge.squirrel_sql.client.mainframe.action.OpenConnectionCommand.access$000(OpenConnectionCommand.java:45)
    at net.sourceforge.squirrel_sql.client.mainframe.action.OpenConnectionCommand$1.run(OpenConnectionCommand.java:104)
    ... 5 more
Caused by: java.sql.SQLException: Unable to connect to database
    at nl.anchormen.sql4es.jdbc.ESConnection.buildClient(ESConnection.java:129)
    at nl.anchormen.sql4es.jdbc.ESConnection.<init>(ESConnection.java:78)
    at nl.anchormen.sql4es.jdbc.ESDriver.connect(ESDriver.java:46)
    at net.sourceforge.squirrel_sql.fw.sql.SQLDriverManager.getConnection(SQLDriverManager.java:133)
    at net.sourceforge.squirrel_sql.client.mainframe.action.OpenConnectionCommand.executeConnect(OpenConnectionCommand.java:167)
    ... 7 more
Caused by: java.lang.NoSuchMethodError: com.google.common.util.concurrent.MoreExecutors.directExecutor()Ljava/util/concurrent/Executor;
    at org.elasticsearch.threadpool.ThreadPool.<clinit>(ThreadPool.java:190)
    at org.elasticsearch.client.transport.TransportClient$Builder.build(TransportClient.java:131)
    at nl.anchormen.sql4es.jdbc.ESConnection.buildClient(ESConnection.java:108)
    ... 11 more

**Comment by corneversloot** [comment]
It seems like the driver is unable to find a method in one of Elastic's dependencies. This is odd since the dependencies are packaged within the jar file... Can you provide a bit more information like: driver version, connection url used and elasticsearch version?

**Comment by sundeepkmr** [comment]
I have attached a file for your reference. Thanks!
[Sql4ES.docx](https://github.com/Anchormen/sql4es/files/503786/Sql4ES.docx)

**Comment by corneversloot** [comment]
It seems a different version of Google Guava is used during execution which leads to the 'NoSuchMethodError' you get. To avoid this situation I build the driver using the Maven shade plugin but for some reason this does not help in your case. Can you try using another client like SQLWorkbench to see if that works (not really a solution I admit but could be a work around for now)

**Comment by sundeepkmr** [comment]
I tried it with SQLWorkBench. But it's not working. It shows 'Unable to connect to database' message when I click on the Test button post configuration.

**Comment by corneversloot** [comment]
Strange, I tested it as well with Elasticsearch 2.4.0 and works fine. However, I do not have a remote desktop to test it on but that should not make a difference as far as I know.

Can you provide the logs of SQLWorkbench (help -> View Logfile), it should show why it is unable to connect?

**Comment by sundeepkmr** [comment]
Here's the log:

2016-10-10 12:46:48 INFO  =================== Log started =================== 
2016-10-10 12:46:48 INFO  Using configdir: C:\Users\gpzikum\.sqlworkbench 
2016-10-10 12:46:48 INFO  Setting default locale to: en 
2016-10-10 12:46:48 INFO  Starting SQL Workbench/J, Build 121 (2016-07-31 23:50) 
2016-10-10 12:46:48 INFO  Java version=1.8.0_102, java.home=C:\Program Files\Java\jre1.8.0_102, vendor=Oracle Corporation, name=Java HotSpot(TM) 64-Bit Server VM 
2016-10-10 12:46:48 INFO  Operating System=Windows 7, version=6.1, platform=amd64 
2016-10-10 12:46:48 INFO  Available memory: 2320MB 
2016-10-10 12:46:49 INFO  Current DPI: 120, Default DPI: 96, scale factor: 1.25 
2016-10-10 12:46:49 INFO  Scaling default fonts by: 1.25 
2016-10-10 12:46:50 INFO  Using sizes: toolbar: 24, menu: 24 
2016-10-10 12:46:56 INFO  Loading connection profiles from C:\Users\gpzikum\.sqlworkbench\WbProfiles.xml 
2016-10-10 12:46:59 INFO  Creating new connection for [{Default group}/SQL for ES] for driver=nl.anchormen.sql4es.jdbc.ESDriver and URL=[jdbc:sql4es://n01sml104.aap.csaa.pri:9300/dtcalert] 
2016-10-10 12:46:59 INFO  Adding ClassLoader URL=file:/C:/Program%20Files/squirrel-sql-3.7.1/lib/sql4es-0.8.2.4.jar 
2016-10-10 12:47:04 ERROR Error connecting to the database using URL=jdbc:sql4es://n01sml104.aap.csaa.pri:9300/dtcalert, username=null Unable to connect to database
java.sql.SQLException: Unable to connect to database
	at nl.anchormen.sql4es.jdbc.ESConnection.buildClient(ESConnection.java:129)
	at nl.anchormen.sql4es.jdbc.ESConnection.<init>(ESConnection.java:78)
	at nl.anchormen.sql4es.jdbc.ESDriver.connect(ESDriver.java:46)
	at workbench.db.DbDriver.connect(DbDriver.java:513)
	at workbench.db.ConnectionMgr.connect(ConnectionMgr.java:244)
	at workbench.db.ConnectionMgr.getConnection(ConnectionMgr.java:172)
	at workbench.gui.profiles.ConnectionGuiHelper$1.run(ConnectionGuiHelper.java:104)
Caused by: NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{172.29.28.71}{172.29.28.71:9300}]]
	at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:290)
	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:207)
	at org.elasticsearch.client.transport.support.TransportProxyClient.execute(TransportProxyClient.java:55)
	at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:288)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:359)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:348)
	at org.elasticsearch.client.support.AbstractClient$IndicesAdmin.execute(AbstractClient.java:1221)
	at org.elasticsearch.client.support.AbstractClient$IndicesAdmin.exists(AbstractClient.java:1241)
	at nl.anchormen.sql4es.jdbc.ESConnection.buildClient(ESConnection.java:122)
	... 6 more

**Comment by corneversloot** [comment]
Well, it sais it cannot find an elasticsearch node on the host you provided. In my experience this can mean a couple of things:
 - there is no route from your machine to n01sml104.aap.csaa.pri. Are you sure you can reach the specified host and there are no firewalls in the way?
 - Elasticsearch is not running or it is running on a port other than 9300
 - you have a cluster name other than the default: 'elasticsearch'. If your cluster name is different you have to specify the cluster name in the connection url like *jdbc:sql4es://n01sml104.aap.csaa.pri:9300/dtcalert?cluster.name=your-cluster-name*

**Comment by sundeepkmr** [comment]
My shield password had the special character '#' in it. I removed it from my password and it worked.

So apparently the problem was with that special character only. Thanks!
