### ISSUE TITLE
Error occurred while creating ad-hoc view in Jaspersoft Server Domain

### ISSUE THREAD

**Issue by MacNale** [Anchormen/sql4es#25]
I am using this driver for creating domain in JasperSoft Server.  I could create the domain. BUT while creating the ad-Hoc view, I received the following error - 

Caused by: java.sql.SQLException: No active index set for this driver. Pleas specify an active index or alias by executing 'USE <index/alias>' first
    at nl.anchormen.sql4es.jdbc.ESStatement.executeQuery(ESStatement.java:62)
    at nl.anchormen.sql4es.jdbc.ESStatement.execute(ESStatement.java:188)
    at nl.anchormen.sql4es.jdbc.ESPreparedStatement.executeQuery(ESPreparedStatement.java:66)
    at org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
    at org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
    at net.sf.jasperreports.engine.query.JRJdbcQueryExecuter.createDatasource(JRJdbcQueryExecuter.java:310)

Could you please help?

**Comment by corneversloot** [comment]
This exception indicates that the driver does not know what index it should use to execute queries against. This is similar as selecting a database before executing queries on tables. You can make an index active by specifying it in the connection url: jdbc:sql4es://hostname:9300/**your-active-index**. Which index is active can by changed by executing the 'USE another-index-name' statement (I do not know how you would do that in JasperSoft though).

Hope this helps!
