### ISSUE TITLE
issue in elasticsearch-2.2.1

### ISSUE THREAD

**Issue by yxdong** [Anchormen/sql4es#3]
In elasticsearch 2.2.1 version, I got an error "Unable to connect to database" when tried to connect.

**Comment by oliv123** [comment]
Hi
Same for me ... I just installed elasticSearch 2.2.1 and SQLworkbenchJ and i have the same message.

**Comment by oliv123** [comment]
Well i have the same message with an older version  ... 2.2.0.

**Comment by corneversloot** [comment]
Hi all, the driver was still build with version 2.1.1 which turned out could not connect to a 2.2.x cluster (thanks for bringing it to my attention!). I have updated the libraries used and a release for 2.2 can be found within the release folder. It passed all the integration tests but it would be good to know if the driver works for you guys on your 2.2.x clusters. So let me know if it works!

**Comment by oliv123** [comment]
Hi ! Thx for your fast reply.
Unfortunately, it still doesn't work on my side with a 2.2.1 ES. :(

log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Exception in thread "main" java.sql.SQLException: Unable to connect to database
	at nl.anchormen.sql4es.jdbc.ESConnection.buildClient(ESConnection.java:122)
	at nl.anchormen.sql4es.jdbc.ESConnection.<init>(ESConnection.java:77)
	at nl.anchormen.sql4es.jdbc.ESDriver.connect(ESDriver.java:46)

**Comment by oliv123** [comment]
OH !  My mistake ! I forgot to create the base name ... It works now.
it's ok with SQLworkbenchJ  but i would like to use it with pentaho (ETL) and unfortunately i have the same error message i had before with the last JAR.

![image](https://cloud.githubusercontent.com/assets/18029723/13999615/699ce436-f13d-11e5-8dcb-76f933734c8c.png)


That's strange cause pentaho is a Java software ... 

any idea ?

**Comment by corneversloot** [comment]
Im not entirely sure what you mean with 'base name' but one thing I can think of is that you have to set the cluster.name if if your clustername is any other than 'elasticsearch'. This can be done within the URL like: jdbc:sql4es://localhost:9300/myindex**?cluster.name=my-es-cluster-name**

The 2.1 version worked with Pentaho (atleast most queries Pentaho threw at it), im writing a blog post about that right now. If you can connect to the cluster using sqlworkbench it should work with Pentaho as well. If not send me the full stacktrace so i can look into it in detail.

**Comment by oliv123** [comment]
When i talk about Pentaho ,  actually it's Kettle (PDI).

I have put the JAR in  the libext folder.

I click on Database connection and i choose  Generic database as you can see on the screenshot above.

I just clicked on TEST to check if the connection can be made and a popup appear with all this


Error connecting to database [test] : org.pentaho.di.core.exception.KettleDatabaseException: 
Error occured while trying to connect to the database

Error connecting to database: (using class nl.anchormen.sql4es.jdbc.ESDriver)
Unable to connect to database


org.pentaho.di.core.exception.KettleDatabaseException: 
Error occured while trying to connect to the database

Error connecting to database: (using class nl.anchormen.sql4es.jdbc.ESDriver)
Unable to connect to database


	at org.pentaho.di.core.database.Database.normalConnect(Database.java:368)
	at org.pentaho.di.core.database.Database.connect(Database.java:317)
	at org.pentaho.di.core.database.Database.connect(Database.java:279)
	at org.pentaho.di.core.database.Database.connect(Database.java:269)
	at org.pentaho.di.core.database.DatabaseFactory.getConnectionTestReport(DatabaseFactory.java:86)
	at org.pentaho.di.core.database.DatabaseMeta.testConnection(DatabaseMeta.java:2464)
	at org.pentaho.ui.database.event.DataHandler.testDatabaseConnection(DataHandler.java:533)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.pentaho.ui.xul.impl.AbstractXulDomContainer.invoke(AbstractXulDomContainer.java:329)
	at org.pentaho.ui.xul.impl.AbstractXulComponent.invoke(AbstractXulComponent.java:139)
	at org.pentaho.ui.xul.impl.AbstractXulComponent.invoke(AbstractXulComponent.java:123)
	at org.pentaho.ui.xul.swt.tags.SwtButton.access$500(SwtButton.java:26)
	at org.pentaho.ui.xul.swt.tags.SwtButton$4.widgetSelected(SwtButton.java:119)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(Unknown Source)
	at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Unknown Source)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:820)
	at org.eclipse.jface.window.Window.open(Window.java:796)
	at org.pentaho.ui.xul.swt.tags.SwtDialog.show(SwtDialog.java:378)
	at org.pentaho.ui.xul.swt.tags.SwtDialog.show(SwtDialog.java:304)
	at org.pentaho.di.ui.core.database.dialog.XulDatabaseDialog.open(XulDatabaseDialog.java:115)
	at org.pentaho.di.ui.core.database.dialog.DatabaseDialog.open(DatabaseDialog.java:62)
	at org.pentaho.di.ui.trans.step.BaseStepDialog$4.widgetSelected(BaseStepDialog.java:515)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(Unknown Source)
	at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Unknown Source)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.pentaho.di.ui.trans.steps.databasejoin.DatabaseJoinDialog.open(DatabaseJoinDialog.java:402)
	at org.pentaho.di.ui.spoon.delegates.SpoonStepsDelegate.editStep(SpoonStepsDelegate.java:136)
	at org.pentaho.di.ui.spoon.Spoon.editStep(Spoon.java:7756)
	at org.pentaho.di.ui.spoon.trans.TransGraph.editStep(TransGraph.java:2756)
	at org.pentaho.di.ui.spoon.trans.TransGraph.mouseDoubleClick(TransGraph.java:705)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(Unknown Source)
	at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Unknown Source)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.pentaho.di.ui.spoon.Spoon.readAndDispatch(Spoon.java:1183)
	at org.pentaho.di.ui.spoon.Spoon.start(Spoon.java:6968)
	at org.pentaho.di.ui.spoon.Spoon.main(Spoon.java:567)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.pentaho.commons.launcher.Launcher.main(Launcher.java:134)
Caused by: org.pentaho.di.core.exception.KettleDatabaseException: 
Error connecting to database: (using class nl.anchormen.sql4es.jdbc.ESDriver)
Unable to connect to database

	at org.pentaho.di.core.database.Database.connectUsingClass(Database.java:504)
	at org.pentaho.di.core.database.Database.normalConnect(Database.java:352)
	... 62 more
Caused by: java.sql.SQLException: Unable to connect to database
	at nl.anchormen.sql4es.jdbc.ESConnection.buildClient(ESConnection.java:122)
	at nl.anchormen.sql4es.jdbc.ESConnection.<init>(ESConnection.java:77)
	at nl.anchormen.sql4es.jdbc.ESDriver.connect(ESDriver.java:46)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at org.pentaho.di.core.database.Database.connectUsingClass(Database.java:490)
	... 63 more
Caused by: java.lang.NoSuchMethodError: org.elasticsearch.common.settings.Settings.settingsBuilder()Lorg/elasticsearch/common/settings/Settings$Builder;
	at nl.anchormen.sql4es.jdbc.ESConnection.buildClient(ESConnection.java:95)
	... 68 more

Hostname       : 
Port           : 1521
Database name  : 



I dont know if it's enough for you to understand the problem.

On my side, i really don't know what I can do more than putting the JAR file in the libext folder...

Thx

**Comment by corneversloot** [comment]
It is enough to understand the problem but im not sure why it happens. It is actually loading and using the driver but looks like it is unable to find one of its dependencies or has another version of it (the elasticsearch library). I altered something in the build process to build a new release (0.8.2.2 jar file) which you can try. Just replace your one with the latest release. To be honest it would surprise me if if solved the problem but it just might :)

**Comment by oliv123** [comment]
I have tried the new JAR ... you are right , it hasn't changed anything ... same error message. :(

**Comment by oliv123** [comment]
WEll i have tried to remove all these Jar .... same issue...

**Comment by corneversloot** [comment]
Im thinking it is not the jar file but the way they are exposed to Pentaho. Turns out that the location of the jar file depends on the Pentaho product and version used. Alse see this page: https://help.pentaho.com/Documentation/5.3/0D0/160/030. Hope it helps

**Comment by oliv123** [comment]
Yes what they say in the documentation is where i put the jar file. ( lib folder )  (Pentaho data integration).
Strange,  it's the 1st time i have this kind of issue with PDI and an external Jar file...

**Comment by oliv123** [comment]
Hi,

I have posted a request on pentaho too.

[http://forums.pentaho.com/showthread.php?203222-Generic-JDBC-and-java-lang-NoSuchMethodError&p=430736#post430736](http://forums.pentaho.com/showthread.php?203222-Generic-JDBC-and-java-lang-NoSuchMethodError&p=430736#post430736)
)
If you have an idea of how you would do if you really needed to resolve this issue ,  just tell me ... I can ask an engineer in my company to check or make some tests  because your project is really interesting if we can use it with tools such as pentaho or other big data tools.

**Comment by corneversloot** [comment]
I think it is some kind of dependency issue since it throws a 'java.lang.NoSuchMethodError'. You are however able to connect to your cluster using SqlWorkbenchJ which implies all the dependencies are present within the jar file. Hence my feeling is that something is getting mixed up with Pentaho which I imagine has lots of dependencies of its own as well. Ill try loading the latest release within my Pentaho BA server (i.e. not DI) to see if i can reproduce the error.

As a side note; sql4es does not implement the full array of SQL/JDBC options which means it might not be able to handle all SQL statements Pentaho throws at it. When I tested it with BA it worked good but it can not for example execut nested select statements like: SELECT ... FROM (SELECT ....) WHERE x IN (SELECT...)

**Comment by corneversloot** [comment]
I have added the driver successfully to Pentaho Business Analytics server (version 6.0.1.0) just by adding it to the tomcat/lib directory. Unfortunately I cannot test it with PDI so it is hard to support you on this issue.

**Comment by oliv123** [comment]
Ok.  I have managed to use the Crate JDBC driver under PDI without any problem ... so  ... your driver is ok  ,  PDI (jdbc) is okay too ... there is a problem in the link ... i guess i wont have any answer from the pentaho forum (too technical question). 
it seems that many user has problem with PDI and elasticsearch, I have seen some topics about it.

Well, for pentaho , i m going to use another solution.

But, we are going to use your driver for another project , really UI/XP oriented and being able to make a SELECT in ES is interesting.

Question: Are you going to maintain it ? (if i find bugs in queries etc .. .. i have found (maybe) strange behavior with String query  =   or  like  )

**Comment by oliv123** [comment]
for the string behavior ... it's just an elasticsearch issue (analyzer) . not the jdbc driver

**Comment by corneversloot** [comment]
Well, just report any issues you encounter and ill do my best to address them in a timely manner.

**Comment by oliv123** [comment]
Good news :)  thank you for your help !

**Comment by fdmorison** [comment]
I runned in the same problem when trying to use it with Kettle (both 6.0 and 7.0). 

Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.elasticsearch.threadpool.ThreadPool

The driver works, but this class cannot be found. I could see it is a FatJar: all dependencies are injected in one single jar. Thus, I really believe your dependencies are conflicting with pentaho's dependencies. I imagine your intention is to make it easier by creating one single distributable jar, but I think it is not a good approach, since it may lead to such annoying problems.

**Comment by corneversloot** [comment]
You are right the goal is to make it easy to make it simple to use the driver. This should however not cause any problems as the fat-jar is shaded. I am not sure if that method is 'bullet proof' though so feel free to improve the project and create a pull request.

**Comment by sudhirkumar1980** [comment]
I am able to connect to ES 5.4 using JDBC connection. But getting following error while using table input.

Field in question is of type long in ES. Do i have to use any any type conversion in sql query ?

2017/06/07 10:31:04 - XXXXXXXXXXXXXXXXXXX - ERROR (version 7.1.0.0-12, build 1 from 2017-05-16 17.18.02 by buildguy) : Unexpected error
2017/06/07 10:31:04 - XXXXXXXXXXXXXXXXXXX - ERROR (version 7.1.0.0-12, build 1 from 2017-05-16 17.18.02 by buildguy) : org.pentaho.di.core.exception.KettleDatabaseException: 
2017/06/07 10:31:04 - XXXXXXXXXXXXXXXXXXX - Couldn't get row from result set
2017/06/07 10:31:04 - XXXXXXXXXXXXXXXXXXX - 
2017/06/07 10:31:04 - XXXXXXXXXXXXXXXXXXX - Unable to get value 'BigNumber(16)' from database resultset, index 0
2017/06/07 10:31:04 - XXXXXXXXXXXXXXXXXXX - Value in column '1' is not of type BigDecimal but is class java.lang.Integer
2017/06/07 10:31:04 - XXXXXXXXXXXXXXXXXXX - 
2017/06/07 10:31:04 - XXXXXXXXXXXXXXXXXXX - 
2017/06/07 10:31:04 - XXXXXXXXXXXXXXXXXXX - 	at org.pentaho.di.core.database.Database.getRow(Database.java:2546)
2017/06/07 10:31:04 - XXXXXXXXXXXXXXXXXXX - 	at org.pentaho.di.core.database.Database.getRow(Database.java:2516)
2017/06/07 10:31:04 - XXXXXXXXXXXXXXXXXXX - 	at org.pentaho.di.core.database.Database.getRow(Database.java:2494)
2017/06/07 10:31:04 - XXXXXXXXXXXXXXXXXXX - 	at org.pentaho.di.trans.steps.tableinput.TableInput.doQuery(TableInput.java:259)
2017/06/07 10:31:04 - XXXXXXXXXXXXXXXXXXX - 	at org.pentaho.di.trans.steps.tableinput.TableInput.processRow(TableInput.java:140)
2017/06/07 10:31:04 - XXXXXXXXXXXXXXXXXXX - 	at org.pentaho.di.trans.step.RunThread.run(RunThread.java:62)
2017/06/07 10:31:04 - XXXXXXXXXXXXXXXXXXX - 	at java.lang.Thread.run(Thread.java:745)
2017/06/07 10:31:04 - XXXXXXXXXXXXXXXXXXX - Caused by: org.pentaho.di.core.exception.KettleDatabaseException: 
2017/06/07 10:31:04 - XXXXXXXXXXXXXXXXXXX - Unable to get value 'BigNumber(16)' from database resultset, index 0
2017/06/07 10:31:04 - XXXXXXXXXXXXXXXXXXX - Value in column '1' is not of type BigDecimal but is class java.lang.Integer
2017/06/07 10:31:04 - XXXXXXXXXXXXXXXXXXX - 
2017/06/07 10:31:04 - XXXXXXXXXXXXXXXXXXX - 	at org.pentaho.di.core.row.value.ValueMetaBase.getValueFromResultSet(ValueMetaBase.java:4964)
2017/06/07 10:31:04 - XXXXXXXXXXXXXXXXXXX - 	at org.pentaho.di.core.database.BaseDatabaseMeta.getValueFromResultSet(BaseDatabaseMeta.java:2107)
2017/06/07 10:31:04 - XXXXXXXXXXXXXXXXXXX - 	at org.pentaho.di.core.database.DatabaseMeta.getValueFromResultSet(DatabaseMeta.java:2950)
2017/06/07 10:31:04 - XXXXXXXXXXXXXXXXXXX - 	at org.pentaho.di.core.database.Database.getRow(Database.java:2538)
2017/06/07 10:31:04 - XXXXXXXXXXXXXXXXXXX - 	... 6 more
2017/06/07 10:31:04 - XXXXXXXXXXXXXXXXXXX - Caused by: java.sql.SQLException: Value in column '1' is not of type BigDecimal but is class java.lang.Integer
2017/06/07 10:31:04 - XXXXXXXXXXXXXXXXXXX - 	at nl.anchormen.sql4es.ESResultSet.getBigDecimal(ESResultSet.java:548)
2017/06/07 10:31:04 - XXXXXXXXXXXXXXXXXXX - 	at org.pentaho.di.core.row.value.ValueMetaBase.getValueFromResultSet(ValueMetaBase.java:4919)
2017/06/07 10:31:04 - XXXXXXXXXXXXXXXXXXX - 	... 9 more
2017/06/07 10:31:04 - XXXXXXXXXXXXXXXXXXX - Finished reading query, closing connection.
