### ISSUE TITLE
Date Time format issue

### ISSUE THREAD

**Issue by sudhirkumar1980** [Anchormen/sql4es#39]
Joda date time can not parse date in format of yyyy-MM-dd HH:mm:ss.SSS

2017/06/14 10:35:55 - ES UEMM_AUDIT_TRAIL - EVENT 67.0 - ERROR (version 7.1.0.0-12, build 1 from 2017-05-16 17.18.02 by buildguy) : Unexpected error
2017/06/14 10:35:55 - XXXXXXXXXXXXXXXXXXXXXXXXXXXXX - ERROR (version 7.1.0.0-12, build 1 from 2017-05-16 17.18.02 by buildguy) : org.pentaho.di.core.exception.KettleDatabaseException: 
2017/06/14 10:35:55 - XXXXXXXXXXXXXXXXXXXXXXXXXXXXX - Couldn't get row from result set
2017/06/14 10:35:55 - XXXXXXXXXXXXXXXXXXXXXXXXXXXXX - 
2017/06/14 10:35:55 - XXXXXXXXXXXXXXXXXXXXXXXXXXXXX - Unable to get value 'Date' from database resultset, index 0
2017/06/14 10:35:55 - XXXXXXXXXXXXXXXXXXXXXXXXXXXXX - Unable to parse Date from '2017-03-09 23:04:14.222' : Invalid format: "2017-03-09 23:04:14.222" is malformed at " 23:04:14.222"
2017/06/14 10:35:55 - XXXXXXXXXXXXXXXXXXXXXXXXXXXXX - 
2017/06/14 10:35:55 - XXXXXXXXXXXXXXXXXXXXXXXXXXXXX - 
2017/06/14 10:35:55 - XXXXXXXXXXXXXXXXXXXXXXXXXXXXX - 	at org.pentaho.di.core.database.Database.getRow(Database.java:2546)
2017/06/14 10:35:55 - XXXXXXXXXXXXXXXXXXXXXXXXXXXXX - 	at org.pentaho.di.core.database.Database.getRow(Database.java:2516)
2017/06/14 10:35:55 - XXXXXXXXXXXXXXXXXXXXXXXXXXXXX - 	at org.pentaho.di.core.database.Database.getRow(Database.java:2494)
2017/06/14 10:35:55 - XXXXXXXXXXXXXXXXXXXXXXXXXXXXX - 	at org.pentaho.di.trans.steps.tableinput.TableInput.doQuery(TableInput.java:259)
2017/06/14 10:35:55 - XXXXXXXXXXXXXXXXXXXXXXXXXXXXX - 	at org.pentaho.di.trans.steps.tableinput.TableInput.processRow(TableInput.java:140)
2017/06/14 10:35:55 - XXXXXXXXXXXXXXXXXXXXXXXXXXXXX - 	at org.pentaho.di.trans.step.RunThread.run(RunThread.java:62)
2017/06/14 10:35:55 - XXXXXXXXXXXXXXXXXXXXXXXXXXXXX - 	at java.lang.Thread.run(Thread.java:745)
2017/06/14 10:35:55 - XXXXXXXXXXXXXXXXXXXXXXXXXXXXX - Caused by: org.pentaho.di.core.exception.KettleDatabaseException: 
2017/06/14 10:35:55 - XXXXXXXXXXXXXXXXXXXXXXXXXXXXX - Unable to get value 'Date' from database resultset, index 0
2017/06/14 10:35:55 - XXXXXXXXXXXXXXXXXXXXXXXXXXXXX - Unable to parse Date from '2017-03-09 23:04:14.222' : Invalid format: "2017-03-09 23:04:14.222" is malformed at " 23:04:14.222"
2017/06/14 10:35:55 - XXXXXXXXXXXXXXXXXXXXXXXXXXXXX - 
2017/06/14 10:35:55 - XXXXXXXXXXXXXXXXXXXXXXXXXXXXX - 	at org.pentaho.di.core.row.value.ValueMetaBase.getValueFromResultSet(ValueMetaBase.java:4964)
2017/06/14 10:35:55 - XXXXXXXXXXXXXXXXXXXXXXXXXXXXX - 	at org.pentaho.di.core.database.BaseDatabaseMeta.getValueFromResultSet(BaseDatabaseMeta.java:2107)
2017/06/14 10:35:55 - XXXXXXXXXXXXXXXXXXXXXXXXXXXXX - 	at org.pentaho.di.core.database.DatabaseMeta.getValueFromResultSet(DatabaseMeta.java:2950)
2017/06/14 10:35:55 - XXXXXXXXXXXXXXXXXXXXXXXXXXXXX - 	at org.pentaho.di.core.database.Database.getRow(Database.java:2538)
2017/06/14 10:35:55 - XXXXXXXXXXXXXXXXXXXXXXXXXXXXX - 	... 6 more
2017/06/14 10:35:55 - XXXXXXXXXXXXXXXXXXXXXXXXXXXXX - Caused by: java.sql.SQLException: Unable to parse Date from '2017-03-09 23:04:14.222' : Invalid format: "2017-03-09 23:04:14.222" is malformed at " 23:04:14.222"
2017/06/14 10:35:55 - XXXXXXXXXXXXXXXXXXXXXXXXXXXXX - 	at nl.anchormen.sql4es.ESResultSet.getTimeFromString(ESResultSet.java:340)
2017/06/14 10:35:55 - XXXXXXXXXXXXXXXXXXXXXXXXXXXXX - 	at nl.anchormen.sql4es.ESResultSet.getTimestamp(ESResultSet.java:388)
2017/06/14 10:35:55 - XXXXXXXXXXXXXXXXXXXXXXXXXXXXX - 	at org.pentaho.di.core.row.value.ValueMetaBase.getValueFromResultSet(ValueMetaBase.java:4946)

**Comment by RaniRaven** [comment]
I am not sure this issue is with SQL4ES, but with your own implementation, what kind of format would you expect ?
