### ISSUE TITLE
Issue with Elasticsearch 5.2.0

### ISSUE THREAD

**Issue by dashrathc** [Anchormen/sql4es#44]
Hi,

I am using Elasticsearch 5.2.0 and querying it in Pentaho 7.1 CDE using sql4es-0.8_5.0.0.jar
JDBC connection is successfully established. But getting following error when querying table,
Caused by: java.lang.NullPointerException
        at nl.anchormen.sql4es.ESResultSet.getStatement(ESResultSet.java:905)
        at org.pentaho.reporting.engine.classic.core.modules.misc.datafactory.sql.ResultSetTableModelFactory.generateDefaultTableModel(ResultSetTableModelFactory.java:296)
        at org.pentaho.reporting.engine.classic.core.modules.misc.datafactory.sql.SimpleSQLReportDataFactory.parametrizeAndQuery(SimpleSQLReportDataFactory.java:328)
        at org.pentaho.reporting.engine.classic.core.modules.misc.datafactory.sql.SimpleSQLReportDataFactory.queryData(SimpleSQLReportDataFactory.java:178)
        at org.pentaho.reporting.engine.classic.core.modules.misc.datafactory.sql.SQLReportDataFactory.queryData(SQLReportDataFactory.java:142)
        at org.pentaho.reporting.engine.classic.core.CompoundDataFactory.queryStaticInternal(CompoundDataFactory.java:172)
        at org.pentaho.reporting.engine.classic.core.CompoundDataFactory.queryStatic(CompoundDataFactory.java:154)
        at org.pentaho.reporting.engine.classic.core.CompoundDataFactory.queryData(CompoundDataFactory.java:67)
        at org.pentaho.reporting.engine.classic.core.cache.CachingDataFactory.queryInternal(CachingDataFactory.java:411)
        at org.pentaho.reporting.engine.classic.core.cache.CachingDataFactory.queryData(CachingDataFactory.java:299)
        at pt.webdetails.cda.dataaccess.PREDataAccess.performRawQuery(PREDataAccess.java:127)

Could anyone please share inputs on this?

Thanks

**Comment by mallim** [comment]
Use a standalone JDBC client and test the SQL first
