### ISSUE TITLE
some problems when integrate into pentaho and saiku

### ISSUE THREAD

**Issue by borderlayout** [Anchormen/sql4es#9]
**Hi,  Corné ,
Firstly, thank you for giving us such a good tool. These days I am looking for jdbc tool for elasticsearch. Sql4es is what I am searching for. But I encounter some problems. could you help me for that? Maybe this is not a defect of sql4es. I use the sql4es in SQLWorkbench and it works well.

1. I followed the article [https://www.anchormen.nl/elasticsearch-as-a-pentaho-source-through-sql4es/] , but it showed exceptions after I opened the analysis report and selected some fields. It seemed that pentaho knows fields name but can not get field data from Elasticserach.  it uses sql4es.8.2.2 es2.2.1 and pentaho business trial 6.1.0. Did you change some configurations when you use sql4es in pentaho?  some screenshots
_https://github.com/borderlayout/test/blob/master/test1.png
https://github.com/borderlayout/test/blob/master/test2.png
https://github.com/borderlayout/test/blob/master/test3.png
https://github.com/borderlayout/test/blob/master/test4.png
https://github.com/borderlayout/test/blob/master/test5.png_

2. I also tried to use sql4es in saiku community edition(saiku CE). [http://community.meteorite.bi/] ,but I encountered another problem.The saiku CE3.7.4 uses apache jackrabbit 2.8.0 which calls lucene-core:3.6.0,  and sql4es(0.8.2.3) uses elasticsearch2.3.2 which also calls lucene(version 5.5.0),
the version of lucene are different and the saiku runs failed.  Could you give me some suggestion for it?**

Gary Wu
email: borderlayout123@gmail.com

the log of pentaho when I select column:
11:34:37,575 ERROR [c] Ticket Number: 1464089677575
11:34:37,578 ERROR [c] Exception in AJAX handler.
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.sql.SQLException: No result found for this query
        at com.pentaho.analyzer.report.ReportRequestService.get(SourceFile:219)
        at com.pentaho.analyzer.content.controller.n.a(SourceFile:168)
        at com.pentaho.analyzer.content.controller.b.b(SourceFile:202)
        at com.pentaho.analyzer.content.AnalyzerContentGenerator.a(SourceFile:311)
        at com.pentaho.analyzer.content.AnalyzerContentGenerator.createContent(SourceFile:157)
        at org.pentaho.platform.web.http.api.resources.GeneratorStreamingOutput.generateContent(GeneratorStreamingOutput.java:236)
        at org.pentaho.platform.web.http.api.resources.GeneratorStreamingOutput.write(GeneratorStreamingOutput.java:163)
        at org.pentaho.platform.web.http.api.resources.GeneratorStreamingOutputProvider.writeTo(GeneratorStreamingOutputProvider.java:54)
        at org.pentaho.platform.web.http.api.resources.GeneratorStreamingOutputProvider.writeTo(GeneratorStreamingOutputProvider.java:33)
        at com.sun.jersey.spi.container.ContainerResponse.write(ContainerResponse.java:306)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1479)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1391)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1381)
        at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:416)
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:538)
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:716)
        at org.pentaho.platform.web.servlet.JAXRSServlet.service(JAXRSServlet.java:109)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
        at org.pentaho.platform.web.servlet.JAXRSServlet.service(JAXRSServlet.java:114)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
        at org.pentaho.platform.web.http.filters.PentahoWebContextFilter.doFilter(PentahoWebContextFilter.java:185)
        at com.pentaho.platform.web.http.filters.PentahoEnterpriseWebContextFilter.doFilter(SourceFile:72)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
        at org.pentaho.platform.web.http.filters.PentahoRequestContextFilter.doFilter(PentahoRequestContextFilter.java:87)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
        at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:399)
        at org.springframework.security.intercept.web.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:109)
        at org.springframework.security.intercept.web.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:83)
        at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:411)
        at org.springframework.security.ui.ExceptionTranslationFilter.doFilterHttp(ExceptionTranslationFilter.java:101)
        at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
        at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:411)
        at org.springframework.security.providers.anonymous.AnonymousProcessingFilter.doFilterHttp(AnonymousProcessingFilter.java:105)
        at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
        at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:411)
        at org.pentaho.platform.web.http.security.RequestParameterAuthenticationFilter.doFilter(RequestParameterAuthenticationFilter.java:191)
        at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:411)
        at org.springframework.security.ui.basicauth.BasicProcessingFilter.doFilterHttp(BasicProcessingFilter.java:174)
        at org.pentaho.platform.web.http.security.PentahoBasicProcessingFilter.doFilterHttp(PentahoBasicProcessingFilter.java:115)
        at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
        at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:411)
        at org.springframework.security.context.HttpSessionContextIntegrationFilter.doFilterHttp(HttpSessionContextIntegrationFilter.java:235)
        at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
        at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:411)
        at org.pentaho.platform.web.http.filters.HttpSessionPentahoSessionIntegrationFilter.doFilter(HttpSessionPentahoSessionIntegrationFilter.java:263)
        at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:411)
        at org.springframework.security.wrapper.SecurityContextHolderAwareRequestFilter.doFilterHttp(SecurityContextHolderAwareRequestFilter.java:91)
        at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
        at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:411)
        at org.springframework.security.util.FilterChainProxy.doFilter(FilterChainProxy.java:188)
        at org.springframework.security.util.FilterToBeanProxy.doFilter(FilterToBeanProxy.java:99)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
        at com.pentaho.ui.servlet.SystemStatusFilter.doFilter(SourceFile:87)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
        at org.pentaho.platform.web.http.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:114)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
        at org.pentaho.platform.web.http.filters.WebappRootForwardingFilter.doFilter(WebappRootForwardingFilter.java:70)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
        at org.pentaho.platform.web.http.filters.PentahoPathDecodingFilter.doFilter(PentahoPathDecodingFilter.java:34)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:522)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1095)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1502)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1458)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.sql.SQLException: No result found for this query
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:206)
        at com.pentaho.analyzer.report.ReportRequestService.get(SourceFile:175)
        ... 86 more
Caused by: java.lang.RuntimeException: java.sql.SQLException: No result found for this query
        at com.pentaho.analyzer.report.ReportManagerImpl.runReport(SourceFile:320)
        at com.pentaho.analyzer.report.ReportManagerImpl.runReport(SourceFile:139)
        at com.pentaho.analyzer.report.ReportRequestService$2.a(SourceFile:275)
        at com.pentaho.analyzer.report.ReportRequestService$2.call(SourceFile:270)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        ... 1 more
Caused by: java.sql.SQLException: No result found for this query
        at nl.anchormen.sql4es.ESQueryState.execute(ESQueryState.java:188)
        at nl.anchormen.sql4es.ESQueryState.execute(ESQueryState.java:172)
        at nl.anchormen.sql4es.jdbc.ESStatement.executeQuery(ESStatement.java:68)
        at org.apache.commons.dbcp.DelegatingStatement.executeQuery(DelegatingStatement.java:208)
        at org.apache.commons.dbcp.DelegatingStatement.executeQuery(DelegatingStatement.java:208)
        at mondrian.rolap.SqlStatement.execute(SqlStatement.java:199)
        at mondrian.rolap.RolapUtil.executeQuery(RolapUtil.java:350)
        at mondrian.rolap.SqlTupleReader.prepareTuples(SqlTupleReader.java:412)
        at mondrian.rolap.SqlTupleReader.readMembers(SqlTupleReader.java:529)
        at mondrian.rolap.SqlMemberSource.getMembersInLevel(SqlMemberSource.java:535)
        at mondrian.rolap.SmartMemberReader.getMembersInLevel(SmartMemberReader.java:147)
        at mondrian.rolap.RolapCubeHierarchy$CacheRolapCubeHierarchyMemberReader.getMembersInLevel(RolapCubeHierarchy.java:724)
        at mondrian.rolap.RolapSchemaReader.getLevelMembers(RolapSchemaReader.java:579)
        at mondrian.rolap.RolapSchemaReader.getLevelMembers(RolapSchemaReader.java:565)
        at mondrian.rolap.RolapCube$RolapCubeSchemaReader.getLevelMembers(RolapCube.java:2829)
        at mondrian.olap.DelegatingSchemaReader.getLevelMembers(DelegatingSchemaReader.java:195)
        at mondrian.olap.Query$QuerySchemaReader.getLevelMembers(Query.java:1535)
        at mondrian.olap.fun.FunUtil.getNonEmptyLevelMembers(FunUtil.java:2235)
        at mondrian.olap.fun.FunUtil.levelMembers(FunUtil.java:2243)
        at mondrian.olap.fun.LevelMembersFunDef$1.evaluateList(LevelMembersFunDef.java:37)
        at mondrian.calc.impl.AbstractListCalc.evaluate(AbstractListCalc.java:65)
        at mondrian.rolap.RolapResult.evaluateExp(RolapResult.java:1089)
        at mondrian.rolap.RolapNamedSetEvaluator.ensureList(RolapNamedSetEvaluator.java:98)
        at mondrian.rolap.RolapNamedSetEvaluator.ensureList(RolapNamedSetEvaluator.java:98)
        at mondrian.rolap.RolapNamedSetEvaluator.evaluateTupleIterable(RolapNamedSetEvaluator.java:66)
        at mondrian.mdx.NamedSetExpr$1.evaluateIterable(NamedSetExpr.java:98)
        at mondrian.calc.impl.AbstractIterCalc.evaluate(AbstractIterCalc.java:50)
        at mondrian.rolap.RolapResult.evaluateExp(RolapResult.java:1089)
        at mondrian.rolap.RolapNamedSetEvaluator.ensureList(RolapNamedSetEvaluator.java:98)
        at mondrian.rolap.RolapNamedSetEvaluator.evaluateTupleIterable(RolapNamedSetEvaluator.java:66)
        at mondrian.mdx.NamedSetExpr$1.evaluateIterable(NamedSetExpr.java:98)
        at mondrian.calc.impl.AbstractIterCalc.evaluate(AbstractIterCalc.java:50)
        at mondrian.rolap.RolapResult.evaluateExp(RolapResult.java:1089)
        at mondrian.rolap.RolapNamedSetEvaluator.ensureList(RolapNamedSetEvaluator.java:98)
        at mondrian.rolap.RolapNamedSetEvaluator.evaluateTupleIterable(RolapNamedSetEvaluator.java:66)
        at mondrian.mdx.NamedSetExpr$1.evaluateIterable(NamedSetExpr.java:98)
        at mondrian.olap.fun.GenerateFunDef$GenerateListCalcImpl.evaluateList(GenerateFunDef.java:113)
        at mondrian.calc.impl.AbstractListCalc.evaluate(AbstractListCalc.java:65)
        at mondrian.rolap.RolapResult.evaluateExp(RolapResult.java:1089)
        at mondrian.rolap.RolapNamedSetEvaluator.ensureList(RolapNamedSetEvaluator.java:98)
        at mondrian.rolap.RolapNamedSetEvaluator.evaluateTupleIterable(RolapNamedSetEvaluator.java:66)
        at mondrian.mdx.NamedSetExpr$1.evaluateIterable(NamedSetExpr.java:98)
        at mondrian.olap.fun.OrderFunDef$CalcImpl.evaluateList(OrderFunDef.java:202)
        at mondrian.calc.impl.AbstractListCalc.evaluate(AbstractListCalc.java:65)
        at mondrian.rolap.RolapResult.evaluateExp(RolapResult.java:1089)
        at mondrian.rolap.RolapNamedSetEvaluator.ensureList(RolapNamedSetEvaluator.java:98)
        at mondrian.rolap.RolapNamedSetEvaluator.evaluateTupleIterable(RolapNamedSetEvaluator.java:66)
        at mondrian.mdx.NamedSetExpr$1.evaluateIterable(NamedSetExpr.java:98)
        at mondrian.rolap.RolapResult.executeAxis(RolapResult.java:976)
        at mondrian.rolap.RolapResult.evalLoad(RolapResult.java:801)
        at mondrian.rolap.RolapResult.loadMembers(RolapResult.java:757)
        at mondrian.rolap.RolapResult.<init>(RolapResult.java:401)
        at mondrian.rolap.RolapConnection.executeInternal(RolapConnection.java:672)
        at mondrian.rolap.RolapConnection.access$000(RolapConnection.java:52)
        at mondrian.rolap.RolapConnection$1.call(RolapConnection.java:623)
        at mondrian.rolap.RolapConnection$1.call(RolapConnection.java:621)
        ... 4 more

**Comment by corneversloot** [comment]
Hi Gary,

I totally missed your issue, im sorry for that. I will see if i can figure out what is going on but have very little time atm. I'll keep you posted. 

- Corné

**Comment by borderlayout** [comment]
Hi Corné, 
Thank you for your reply. 
For Point 2, these days I tried saiku2.x community edition and it can work with sql4es. After resolving multi-guava version confliction, saiku can get data from elasticsearch. WoW.  :)
saiku3.x has a complicated relationship in its third-party libraries especially for lucene package. I didn't find a easy way to resolve that.
Gary

**Comment by corneversloot** [comment]
Well the sql4es jar file is build using the shade plugin so you should not run into these dependency conflicts... Not sure if / how i can support you any further so ill close this issue. Feel free to open up a new one when you encounter something :)
